[zk-176] Update the default sign_data
zk-experiments/zkevm-circuits pull request #24
Opened 2023-07-21 10:38 UTC by maxatdeltafi

## Changes

- Change 1
port from scroll-tech/zkevm-circuits/pull/560

Description
This PR aims to refactor how the default sign data is created. Previously, the default sign data is generated through
signing the msg(b"1") using 0x01 as the private key and 0x01 as the randomness k. This is different than the sign data of the padding tx that we use in the tx circuit and pi circuit. Therefore, this sign data is kind of out dated.

Type of change
 Refactor/Cleanup
Contents
The default sign data is updated as the sign data of default padding tx(a pre-eip155 tx signed by a dummy private key 0x01)

2023-07-21 15:56 UTC, RuiLiu3 approved these changes

2023-07-21 16:00 UTC, RuiLiu3 commented
fix Rustfmt （CI failed）

2023-07-21 17:35 UTC, pjxthy requested changes

2023-07-21 17:35 UTC, pjxthy commented on eth-types/src/sign_types.rs
> +    // FIXME: need to check if this is deterministic which means sig is fixed.
1/ FIXME -> TODO (@author) to unify TODOs
2/ Let us get this issue fixed in this Pr instead of waiting for TODOs

2023-07-21 17:35 UTC, pjxthy commented on bus-mapping/src/evm/opcodes/precompiles/ecrecover.rs
> +                let mut u256_bytes = [0u8; 32];
we should move 32, 12, magic numbers to a constatn file

2023-07-21 17:35 UTC, pjxthy commented on eth-types/src/sign_types.rs
> +    let mut sk_be_scalar = [0u8; 32];
magic number

2023-07-21 17:35 UTC, pjxthy commented on eth-types/src/sign_types.rs
> +    sk_be_scalar[31] = 1_u8;
31 = 32 defined constatn -1

2023-07-21 17:35 UTC, pjxthy commented on eth-types/src/sign_types.rs
> +/// Generate a dummy pre-eip155 tx in which
1/ better readme
2/ add unit tests

2023-07-21 17:35 UTC, pjxthy commented on bus-mapping/src/evm/opcodes/precompiles/ecrecover.rs
> +            fn h160_to_u256(h160: H160) -> U256 {
add unit tests for this updated logic

2023-07-21 17:35 UTC, pjxthy commented on eth-types/src/sign_types.rs
> +        let (tx_req, sig) = get_dummy_tx();
add unit tests for this updated logic

2023-07-21 17:36 UTC, pjxthy commented
port from scroll/zkevm-circuits/pull/560

-> let us avoid mentioning scroll PRs in our PR
-> replace it with real logic change next time

2023-07-21 17:37 UTC, pjxthy commented
no need to have change 1, 2, 3 in the descpriont

just bullet by bullet change descriptions. i have updated the pr description this time.

2023-07-22 01:56 UTC, maxatdeltafi commented on eth-types/src/sign_types.rs
> +    sk_be_scalar[31] = 1_u8;
done

2023-07-22 01:56 UTC, maxatdeltafi commented on eth-types/src/sign_types.rs
> +    let mut sk_be_scalar = [0u8; 32];
done

2023-07-22 01:56 UTC, maxatdeltafi commented on bus-mapping/src/evm/opcodes/precompiles/ecrecover.rs
> +                let mut u256_bytes = [0u8; 32];
done

2023-07-22 02:43 UTC, maxatdeltafi commented on eth-types/src/sign_types.rs
> +    // FIXME: need to check if this is deterministic which means sig is fixed.
remote the fixme, here is fixed tx

2023-07-22 02:45 UTC, maxatdeltafi commented on eth-types/src/sign_types.rs
> +/// Generate a dummy pre-eip155 tx in which
done

2023-07-22 02:45 UTC, maxatdeltafi commented on bus-mapping/src/evm/opcodes/precompiles/ecrecover.rs
> +            fn h160_to_u256(h160: H160) -> U256 {
done

2023-07-22 02:57 UTC, maxatdeltafi commented on eth-types/src/sign_types.rs
> +        let (tx_req, sig) = get_dummy_tx();
done

2023-07-22 03:31 UTC, pjxthy approved these changes

2023-07-22 03:31 UTC, merged