Execution state gadget for EcAdd precompile call
zk-experiments/zkevm-circuits pull request #4
Opened 2023-07-19 16:51 UTC by pjxthy

Changes:
- Merge PR difference: https://github.com/scroll-tech/zkevm-circuits/pull/598

Test Plan:
- Green CIs

2023-07-19 17:14 UTC, akloopx requested changes

2023-07-19 17:14 UTC, akloopx commented on bus-mapping/src/evm/opcodes/callop.rs
> +                let output_bytes = if call.is_success() && !result.is_empty() {
why remove all 'call.call_data_length > 0' condition?

2023-07-19 17:14 UTC, akloopx commented on bus-mapping/src/evm/opcodes/callop.rs
> +                let returned_bytes = if call.is_success() && length > 0 {
ditto

2023-07-19 17:17 UTC, RuiLiu3 commented on zkevm-circuits/src/evm_circuit/util/precompile_gadget.rs
> -            Box::new(|_cb| { /* Bn128Add */ }),
What does Bn128Add mean? is the new add code to implement the logic about it?

2023-07-19 17:19 UTC, RuiLiu3 approved these changes

2023-07-19 17:20 UTC, merged

2023-07-20 05:02 UTC, dfixx commented on zkevm-circuits/src/evm_circuit/util/precompile_gadget.rs
> -            Box::new(|_cb| { /* Bn128Add */ }),
Bn128Add是一种Precompile方式，后面关联着stateExecute，这个跟具体的EVM里的Cell有关系，也跟gas有关系，但是这个具体的操作意思，我还没看懂。。。